config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'
  resources :ideas
  resources :categories, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :color, inclusion: {in: %w(blue green red), message: "mavi yeşil kırmızı olabilir"}
  validates :title, uniqueness: true

  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true ,length: {minimum: 10}
  validates :description, presence: true, length: {maximum: 500}
  validate :check_planned_to
  def check_planned_to
    if planned_to.present? && planned_to < Date.today
      errors.add(:planned_to, "Geçmişte bir tarih olamaz")
    end
  end

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :update, :edit, :destroy]


  def new
    @idea=Idea.new
    load_categories
  end

  def index
    @ideas = Idea.all
  end

  def show

  end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      flash[:success] = 'Islem basariyla tamamlandi.'
      redirect_to idea_path(@idea)
    else
      load_categories
      render :new
    end
  end

  def edit
    load_categories
  end

  def update
    if @idea.update(idea_params)
      redirect_to idea_path(@idea)
    else
      load_categories
      render :edit
    end
  end

  def destroy

    @idea.destroy
    redirect_to ideas_path
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :description, :planned_to, :category_id)
  end
  def load_categories
    @categories = Category.all.collect {|c| [c.title,c.id]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/application/_flash.html.erb
<% if !flash.empty? %>
    <div id="flash">
      <% flash.keys.each do |k| %>
          <div class="<%= k %>">
            <%= flash[k] %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>


<% @categories.each do |c| %>
    <%= link_to c.title, category_path(c) %><br />
<%end%>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<% @category.ideas.each do |idea| %>
    ID: <%= idea.id%><br>
    Title:
    <%= link_to (idea.title), idea_path(idea) %><br>
    Desc:<%= idea.description%><br>
<%end%>

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %>

    <%= f.label :title%>
    <%= f.text_field :title, placeholder: 'title', class: "form-control input-sm" %><br />
    <%= f.label :description%><br />
    <%= f.text_area :description, placeholder: 'description',rows: 10  %><br />
    <%= f.label :planned_to%>
    <%= f.date_field :planned_to, placeholder: 'planned_to'%><br />
    <%= f.select :category_id, @categories %><br />
    <%= f.submit 'Gonder'%>


<%end%>

app/views/ideas/edit.html.erb
<h1>Editing : <%= @idea.title %></h1>

<% if @idea.errors.any? %>
    <h3>
      <%= @idea.errors.full_messages.join(", ") %>
    </h3>
<%end%>




  <%= render "form" %>
</form>

app/views/ideas/index.html.erb
Listing Ideas <br />

  <%= @ideas.count %><br />

  <% @ideas.each do |ideas| %>
       ID: <%= ideas.id%>
       Title:
       <%= link_to (ideas.title), idea_path(ideas) %>
       Desc:<%= ideas.description%>
       <%= link_to  "Delete idea", idea_path(ideas) , method: :delete%><br />
  <%end%>

<%= link_to "New Idea", new_idea_path %>

app/views/ideas/new.html.erb
<h1>Create a new Idea</h1>

<% if @idea.errors.any? %>
    <h3>
      <%= @idea.errors.full_messages.join(", ") %>
    </h3>
<%end%>

<form action="<%=ideas_path%>" method="post"><br />
 <%= render "form" %>
</form>
<%= link_to "Back to Ideas List", ideas_path %><br />

app/views/ideas/show.html.erb
Display Idea


  ID: <%= @idea.id %> <br />
  Title: <%= @idea.title %> <br />
  Desc: <%= @idea.description %> <br />
  Category: <%= @idea.category.title %><br />


<%= link_to "Back to Ideas List", ideas_path %><br />
<%= link_to  "Edit idea", edit_idea_path(@idea) %><br />
<%= link_to  "Delete idea", idea_path(@idea) , method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "flash" %>
    <%= yield %>
  </body>
</html>